### ISSUE TITLE
Documentation/Help Possible?

### ISSUE THREAD

**Issue by djangomcdjangerson** [uptick/django-user-defined-fields#14]
I've been able to get off the ground with this library to a degree. but I'm struggling with getting anything other than a textarea with an empty JSON dict to render. I wouldn't be opposed to building out my own widget system in django template and jquery, but I feel like I'm just seriously missing the entire formfield rendering idea. Would any of you all be able to shed a little light on this? I feel dumb haha.
If nothing else, I was trying to find a good example of a correctly formatted JSON string for a filled out field. I think with that, I could fill in the blanks and render fields, etc. Hate to bother anyone but I noticed that a couple of the contributors here are active on the platform, thought I'd reach out.

**Comment by djangomcdjangerson** [comment]
After re-reviewing the code and gleaning just a little more information, I was able to guess at the correct format. In case there is never a reply, here is a bit of information for any internet passerby. The correct value storage format for the ExtraField field on your model is {"extrafield_name_1": "value", "extrafield_name_2": "value_2"}

**Comment by jarekwg** [comment]
Hiya @djangomcdjangerson!

Glad you worked it out. If you have a poke around the example folder you should be able to glean more info there. Lettuce know if you have any further questions!

**Comment by djangomcdjangerson** [comment]
I was able to make some minor changes to the app and do some trickery in my own to get it integrated pretty well seamlessly. I'm very pleased!
